export const WorksData = [
  {
    title: 'Portfolio',
    alt: 'portfolio',
    desc: 'Next/TS/TailwindCSS',
    href: 'https://github.com/taichi-de/my-portfolio',
    img: '/taizen-dev.png',
    privateRepo: false,
    // comments: 'This portfolio site',
  },
  {
    title: 'Tischify',
    alt: 'Tischify',
    desc: 'Vue3/Pinia/Vuetify',
    href: 'https://github.com/Tischify/Tischify',
    img: '/tischify-demo.png',
    privateRepo: true,
  },
  {
    title: 'PresentTalesLP',
    alt: 'presenttalesLP',
    desc: 'HTML/Sass/Gulp',
    href: 'https://github.com/taichi-de/PresentTalesLP',
    img: '/presenttalesLP.png',
    privateRepo: false,
  },
  {
    title: 'E-commerce App',
    alt: 'E-commerce App',
    desc: 'Nuxt3/Pinia/Vuetify',
    href: '#',
    img: '/e-commerce.png',
    privateRepo: true,
  },
  {
    title: 'Dashboard App',
    alt: 'Dashboard App',
    desc: 'Next.js/TS/Flask',
    href: 'https://github.com/taichi-de/dashboard-Tailwindcss/tree/main',
    img: '/dashboard-app.png',
    privateRepo: true,
  },
  {
    title: 'Taizen Blog',
    alt: 'taizen-blog',
    desc: 'Next.js/MantineUI/MicroCMS',
    href: 'https://github.com/taichi-de/taizen-note',
    img: '/taizen-note.png',
    privateRepo: false,
  },
];
